### PR TITLE
Add AWS Linked Account Role

### PR DESCRIPTION
**Pull request by GCelichowski**
- Remove Centralized Monitoring Scripts that have been factored to their own OSS repo
- Add Linked Account roles
- Reorganize AWS Role Files in to folders

### CODE REVIEW

**Comment by joshk0** [comment]
PTO, can you have someone else on the team review? Thanks!

**Review by acham1 — COMMENTED** [review]
Lgtm!

- was sweeping `scripts/` intended?
- were there any major diffs b/t the linked account and payer account roles, or was it a straight lift-n-shift?
- with the re-org, wdyt of dropping a brief README in the new directories to describe what they're for?

**Comment by GCelichowski** [comment]
> * was sweeping `scripts/` intended?
yeah, that code has been factored out into the OSS repo
> * were there any major diffs b/t the linked account and payer account roles, or was it a straight lift-n-shift?
minor differences- omission of CUR details, and additional items that may be of interest in linked accounts
> * with the re-org, wdyt of dropping a brief README in the new directories to describe what they're for?
will do

**Review by acham1 — APPROVED** [review]
lgtm!

**Comment by acham1** [comment]
> > * was sweeping `scripts/` intended?
> >   yeah, that code has been factored out into the OSS repo
> > * were there any major diffs b/t the linked account and payer account roles, or was it a straight lift-n-shift?
> >   minor differences- omission of CUR details, and additional items that may be of interest in linked accounts
> > * with the re-org, wdyt of dropping a brief README in the new directories to describe what they're for?
> >   will do

Thanks for the updates! Feel free to self-approve if you end up adding the READMEs too, but non-blocking.

**Pull request merged**
